# Generated by Django 3.0.5 on 2020-04-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200424_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announce',
            name='published_date',
        ),
    ]
